### ISSUE TITLE
Caleb: AssignedTests vs AvailableTests

### ISSUE THREAD

**Issue by scotrenz** [Yash-Training2018/ota#138]
Trainee Controller assignedtest.htm is calling showAvailableTests which is then calling testService.getAssignedTestsByUserId

**Comment by CalebReiter** [comment]
Oh yes. The method should have been changed to showAssignedTests.

**Comment by sjay93** [comment]
@CalebReiter will make the changes and will push into develop. We don't have to make changes at our end. Is it correct?

**Comment by scotrenz** [comment]
@sjay93 correct, @CalebReiter and I will fix it

**Comment by scotrenz** [comment]
@CalebReiter if this is something you've already fixed in your branch but hasn't been merged we will be reviewing all the awaiting merges tomorrow but you will have to pull dev first and we can go over merge conflicts if you have any
