### ISSUE TITLE
Zack: TopicServiceImpl getTopicsWithTest shouldn't return a list

### ISSUE THREAD

**Issue by scotrenz** [Yash-Training2018/ota#151]
There is only one topic per test, this method should return only one topic object

**Comment by zachdog6** [comment]
It return all topics that have a test associated with them.

**Comment by zachdog6** [comment]
It is not associated with 1 specific test, but ALL tests

**Comment by scotrenz** [comment]
Ok, I misunderstood the method name thought it was getting mutliple topics for one test.

What is this method used to accomplish?

**Comment by zachdog6** [comment]
I need the topic names for each test for the test-default and test-details pages, but not all topics have a test associated with it. I use this to get all of those topics.

I use a much better method in my recent branches, so this method is outdated and will be removed whenever I get those branches in.

**Comment by scotrenz** [comment]
Cool
We are going through merges tomorrow and walking through with everybody that has code ready.
