### ISSUE TITLE
Titles on jsp pages

### ISSUE THREAD

**Issue by Connor-Brown** [Yash-Training2018/ota#191]
Below is a list of all the jsp pages that need titles:

All admin jsp pages:
 - batch-default.jsp
 - batch-details.jsp
 - overall-reports.jsp
 - techwise-reports.jsp
 - admin-dashboard.jsp
 - trainee-selector.jsp

All Trainer jsp pages:
 - create-batch.jsp
 - overall-report.jsp
 - techwise-detail.jsp

All Util jsp pages:
 - login.jsp
 - register.jsp
 - registration-confirmation.jsp

**Comment by scotrenz** [comment]
I got a few, wasn't thorough though

**Comment by ArpMichaelB** [comment]
I added titles to a good portion of these pages in my branch that addresses another issue (#273)
