### ISSUE TITLE
Anyone: deleteSpecificTraineeTest() method in the Trainer Controller

### ISSUE THREAD

**Issue by neel136846** [Yash-Training2018/ota#250]
This method doesn't do what the method name says and there is no documentation to describe what it should do.

What does it do? Should it be deleted?

**Comment by zachdog6** [comment]
I didn't make it

**Comment by neel136846** [comment]
Okay, anyone know who this belongs to?

**Comment by nmparker** [comment]
The deleteSpecificTraineeTest(Model model) and showSpecificTraineeTest(Mode model) methods should be deleted, I removed them with my user story's merge but they are back. Who ever deletes them please be sure to delete the showSpecificTraineeTest method that looks like this:

 @RequestMapping(value = "/test-detail.htm", method = RequestMethod.GET)
    public String showSpecificTraineeTest(Model model) {
        return "trainer/trainee/detail/techwise-detail";
    }

and not the showSpecificTraineeTest method with my authorship on it.

**Comment by neel136846** [comment]
Thanks boo 🤰
